env:
  browser: true
  es2021: true
extends: eslint:recommended
globals:
  protobuf: readonly
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:

  block-scoped-var:
    - error
  camelcase:
    - error
  consistent-return:
    - error
  default-case:
    - error
  default-case-last:
    - error
  default-param-last:
    - error
  dot-notation:
    - error
  eqeqeq:
    - error
    - always
  func-names:
    - error
    - always
  init-declarations:
    - error
    - always
  multiline-comment-style:
    - error
    - separate-lines
  new-cap:
    - error
  no-bitwise:
    - error
    - allow:
      - ">>>"
      - ">>"
      - "<<"
  no-caller:
    - error
  no-continue:
    - error
  no-eq-null:
    - error
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-extra-label:
    - error
  no-floating-decimal:
    - error
  no-implicit-coercion:
    - error
  no-implicit-globals:
    - error
    - lexicalBindings: true
  no-implied-eval:
    - error
  no-invalid-this:
    - error
  no-iterator:
    - error
  no-label-var:
    - error
  no-labels:
    - error
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-multi-assign:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-object:
    - error
  no-new-wrappers:
    - error
  no-octal-escape:
    - error
  no-param-reassign:
    - error
  no-proto:
    - error
  no-return-assign:
    - error
    - always
  no-return-await:
    - error
  no-script-url:
    - error
  no-sequences:
    - error
    - allowInParentheses: false
  no-shadow:
    - error
    - builtinGlobals: false
      hoist:          all
  no-throw-literal:
    - error
  no-unneeded-ternary:
    - error
  no-unused-expressions:
    - error
  no-useless-call:
    - error
  no-useless-computed-key:
    - error
  no-useless-concat:
    - error
  no-useless-rename:
    - error
  no-useless-return:
    - error
  no-var:
    - error
  no-void:
    - error
  no-with:
    - error
  object-shorthand:
    - error
  one-var:
    - error
    - never
  one-var-declaration-per-line:
    - error
    - always
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  prefer-exponentiation-operator:
    - error
  prefer-numeric-literals:
    - error
  prefer-object-spread:
    - error
  prefer-promise-reject-errors:
    - error
  prefer-regex-literals:
    - error
    - disallowRedundantWrapping: true
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  quotes:
    - error
    - double
  radix:
    - error
    - as-needed
  semi:
    - error
    - always
  spaced-comment:
    - error
    - always
  yoda:
    - error
    - never

  arrow-spacing:
    - error
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-style:
    - error
    - first
  dot-location:
    - error
  eol-last:
    - error
  key-spacing:
    - error
    - mode: minimum
  keyword-spacing:
    - error
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - code:                   105
      ignoreComments:         true
      ignoreRegExpLiterals:   true
      ignoreStrings:          true
      ignoreTemplateLiterals: true
      tabWidth:               2
  max-statements-per-line:
    - error
    - max: 10
  no-tabs:
    - error
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  rest-spread-spacing:
    - error
    - never
  semi-spacing:
    - error
    - before: false
      after:  true
  semi-style:
    - error
  space-unary-ops:
    - error
    - words:    true
      nonwords: false
      overrides:
        typeof: false
  switch-colon-spacing:
    - error
  unicode-bom:
    - error
  wrap-iife:
    - error
    - inside
